
Cell 4:
Current branch     : uat
Current environment: uat

Cell 5:

Cell 7:
Index(['ID', 'LONGDISTANCE', 'INTERNATIONAL', 'LOCAL', 'DROPPED', 'PAYMETHOD',
       'LOCALBILLTYPE', 'LONGDISTANCEBILLTYPE', 'USAGE', 'RATEPLAN', 'GENDER',
       'STATUS', 'CHILDREN', 'ESTINCOME', 'CAROWNER', 'AGE', 'CREDITCARD',
       'DOB', 'ADDRESS_1', 'CITY', 'STATE', 'ZIP', 'ZIP4', 'LONGITUDE',
       'LATITUDE', 'CHURN'],
      dtype='object')

Cell 8:

Cell 11:

Cell 13:

Cell 16:

Cell 17:
              precision    recall  f1-score   support

         0.0       0.96      0.90      0.93       335
         1.0       0.86      0.95      0.90       231

    accuracy                           0.92       566
   macro avg       0.91      0.92      0.92       566
weighted avg       0.92      0.92      0.92       566


Cell 21:

Cell 25:

Creating a new deployment space - churn-uat

Space has been created. However some background setup activities might still be on-going. Check for 'status' field in the response. It has to show 'active' before space can be used. If it's not 'active', you can monitor the state with a call to spaces.get_details(space_id). Alternatively, use background_mode=False when calling client.spaces.store().

Cell 26:
-----------------------------  ------------------------------------  ----
NAME                           ASSET_ID                              TYPE
default_py3.6                  0062b8c9-8b7d-44a0-a9b9-46c416adcbd9  base
runtime-22.1-r3.6              018ebea5-1d1f-5fec-b93e-5e2ab30e7f38  base
kernel-spark3.2-scala2.12      020d69ce-7ac1-5e68-ac1a-31189867356a  base
pytorch-onnx_1.3-py3.7-edt     069ea134-3346-5748-b513-49120e15d288  base
scikit-learn_0.20-py3.6        09c5a1d0-9c1e-4473-a344-eb7b665ff687  base
spark-mllib_3.0-scala_2.12     09f4cff0-90a7-5899-b9ed-1ef348aebdee  base
pytorch-onnx_rt22.1-py3.9      0b848dd4-e681-5599-be41-b5f6fccc6471  base
ai-function_0.1-py3.6          0cdb0f1e-5376-4f4d-92dd-da3b69aa9bda  base
shiny-r3.6                     0e6e79df-875e-4f24-8ae9-62dcc2148306  base
pytorch_1.1-py3.6              10ac12d6-6b30-4ccd-8392-3e922c096a92  base
runtime-22.1-py3.9             12b83a17-24d8-5082-900f-0ab31fbfd3cb  base
scikit-learn_0.22-py3.6        154010fa-5b3b-4ac1-82af-4d5ee5abbc85  base
pytorch-onnx_1.7-py3.8-edt     1b199910-c7d5-5af4-b8f1-e86b760f9779  base
default_r3.6                   1b70aec3-ab34-4b87-8aa0-a4a3c8296a36  base
pytorch-onnx_rt22.1-py3.9-edt  1d362186-7ad5-5b59-8b6c-9d0880bde37f  base
spark-mllib_3.2                20047f72-0a98-58c7-9ff5-a77b012eb8f5  base
runtime-22.1-py3.9-cuda        26215f05-08c3-5a41-a1b0-da66306ce658  base
do_py3.8                       295addb5-9ef9-547e-9bf4-92ae3563e720  base
autoai-ts_3.8-py3.8            2aa0c932-798f-5ae9-abd6-15e0c2402fb5  base
tensorflow_1.15-py3.6          2b73a275-7cbf-420b-a912-eae7f436e0bc  base
pytorch_1.2-py3.6              2c8ef57d-2687-4b7d-acce-01f94976dac1  base
spark-mllib_2.3                2e51f700-bca0-4b0d-88dc-5c6791338875  base
pytorch-onnx_1.1-py3.6-edt     32983cea-3f32-4400-8965-dde874a8d67e  base
spark-mllib_3.0-py37           36507ebe-8770-55ba-ab2a-eafe787600e9  base
xgboost_0.82-py3.6             39e31acd-5f30-41dc-ae44-60233c80306e  base
pytorch-onnx_1.2-py3.6-edt     40589d0e-7019-4e28-8daa-fb03b6f4fe12  base
autoai-ts_rt22.1-py3.9         4269d26e-07ba-5d40-8f66-2d495b0c71f7  base
autoai-obm_3.0                 42b92e18-d9ab-567f-988a-4240ba1ed5f7  base
ai-function_0.2-py3.6          435bfa8f-ddae-549a-826a-894368887231  base
pmml-3.0_4.3                   493bcb95-16f1-5bc5-bee8-81b8af80e9c7  base
spark-mllib_2.4-r_3.6          49403dff-92e9-4c87-a3d7-a42d0021c095  base
xgboost_0.90-py3.6             4ff8d6c2-1343-4c18-85e1-689c965304d3  base
pytorch-onnx_1.1-py3.6         50f95b2a-bc16-43bb-bc94-b0bed208c60b  base
autoai-ts_3.9-py3.8            52c57136-80fa-572e-8728-a5e7cbb42cde  base
spark-mllib_2.4-scala_2.11     55a70f99-7320-4be5-9fb9-9edb5a443af5  base
spark-mllib_3.0                5c1b0ca2-4977-5c2e-9439-ffd44ea8ffe9  base
autoai-obm_2.0                 5c2e37fa-80b8-5e77-840f-d912469614ee  base
spss-modeler_18.1              5c3cad7e-507f-4b2a-a9a3-ab53a21dee8b  base
cuda-py3.8                     5d3232bf-c86b-5df4-a2cd-7bb870a1cd4e  base
autoai-kb_3.1-py3.7            632d4b22-10aa-5180-88f0-f52dfb6444d7  base
pytorch-onnx_1.7-py3.8         634d3cdc-b562-5bf9-a2d4-ea90a478456b  base
tensorflow_2.4-py3.7           65e171d7-72d1-55d9-8ebb-f813d620c9bb  base
spss-modeler_18.2              687eddc9-028a-4117-b9dd-e57b36f1efa5  base
pytorch-onnx_1.2-py3.6         692a6a4d-2c4d-45ff-a1ed-b167ee55469a  base
spark-mllib_2.4-py37           7abc992b-b685-532b-a122-a396a3cdbaab  base
caffe_1.0-py3.6                7bb3dbe2-da6e-4145-918d-b6d84aa93b6b  base
pytorch-onnx_1.7-py3.7         812c6631-42b7-5613-982b-02098e6c909c  base
cuda-py3.6                     82c79ece-4d12-40e6-8787-a7b9e0f62770  base
hybrid_0.1                     8c1a58c6-62b5-4dc4-987a-df751c2756b6  base
pytorch-onnx_1.3-py3.7         8d5d8a87-a912-54cf-81ec-3914adaa988d  base
-----------------------------  ------------------------------------  ----
Note: Only first 50 records were displayed. To display more use 'limit' parameter.

Cell 27:
---------------------------------------------------------------------------
ApiException                              Traceback (most recent call last)
/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/models.py in _publish_from_object_cloud(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names, project_id)
   2467                 query_param_for_repo_client = self._client._params()
-> 2468                 saved_model = self._client.repository._ml_repository_client.models.save(model_artifact,
   2469                                                                                         query_param=query_param_for_repo_client)

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py in save(self, artifact, query_param)
    212         if artifact.meta.prop(MetaNames.TYPE).startswith("scikit-learn"):
--> 213             return self._save_scikit_pipeline_model(artifact, query_param)
    214         elif artifact.meta.prop(MetaNames.TYPE).startswith("xgboost"):

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py in _save_scikit_pipeline_model(self, artifact, query_param)
    265             print(traceback.format_exc())
--> 266             raise e
    267 

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py in _save_scikit_pipeline_model(self, artifact, query_param)
    253             if artifact.uid is None:
--> 254                 model_artifact = self._create_pipeline_model(artifact, query_param)
    255             else:

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py in _create_pipeline_model(self, model_artifact, query_param)
    513     def _create_pipeline_model(self, model_artifact, query_param=None):
--> 514         model_artifact = self._create_pipeline_model_v4_cloud(model_artifact, query_param)
    515         return model_artifact

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py in _create_pipeline_model_v4_cloud(self, model_artifact, query_param)
   1147 
-> 1148         model_output = self.repository_api.ml_assets_model_creation_v4_cloud(model_input, query_param,headers)
   1149         if model_output is not None:

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/apis/repository_api.py in ml_assets_model_creation_v4_cloud(self, models_input, query_param, headers, **kwargs)
    300         else:
--> 301             (data) = self.ml_assets_model_creation_v4_cloud_with_http_info(models_input,query_param, headers, **kwargs)
    302             return data

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/apis/repository_api.py in ml_assets_model_creation_v4_cloud_with_http_info(self, models_input, query_param, headers, **kwargs)
    373 
--> 374         return self.api_client.call_api(resource_path, 'POST',
    375                                             path_params,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    385         if callback is None:
--> 386             return self.__call_api(resource_path, method,
    387                                    path_params, query_params, header_params,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only)
    205 
--> 206         response_data = self.request(method, url,
    207                                      query_params=query_params,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py in request(self, method, url, query_params, headers, post_params, body)
    420         elif method == "POST":
--> 421             return self.rest_client.POST(url,
    422                                          query_params=query_params,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/rest.py in POST(self, url, headers, query_params, post_params, body)
    229     def POST(self, url, headers=None, query_params=None, post_params=None, body=None):
--> 230         return self.request("POST", url,
    231                             headers=headers,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/rest.py in request(self, method, url, query_params, headers, body, post_params)
    201         if r.status not in range(200, 206):
--> 202             raise ApiException(http_resp=r)
    203 

ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 13 Sep 2022 17:06:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '287', 'Connection': 'keep-alive', 'Server': '---', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {
  "trace": "446d873f1k46c2753849bl09w6d435iae944",
  "errors": [{
    "code": "invalid_request_entity",
    "message": "Invalid request entity: Unsupported model type 'scikit-learn_0.23'",
    "more_info": "https://cloud.ibm.com/apidocs/machine-learning"
  }],
  "status_code": "400"
}


During handling of the above exception, another exception occurred:

WMLClientError                            Traceback (most recent call last)
/tmp/1000630000/ipykernel_159/2219062619.py in <module>
      7 }
      8 
----> 9 stored_model_details = client.repository.store_model(pipeline,
     10                                                meta_props=metadata,
     11                                                training_data=X_train,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/repository.py in store_model(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names, subtrainingId)
    409             """
    410 
--> 411         return self._client._models.store(model, meta_props=meta_props, training_data=training_data, training_target=training_target, pipeline=pipeline, feature_names=feature_names, label_column_names=label_column_names,subtrainingId=subtrainingId)
    412 
    413     @docstring_parameter({'str_type': STR_TYPE_NAME})

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/models.py in store(self, model, meta_props, training_data, training_target, pipeline, version, artifactid, feature_names, label_column_names, subtrainingId)
   1501             else:
   1502                 if self._client.CLOUD_PLATFORM_SPACES or self._client.ICP_35 or self._client.ICP_40 or self._client.ICP_45:
-> 1503                     saved_model = self._publish_from_object_cloud(model=model, meta_props=meta_props,
   1504                                                             training_data=training_data,
   1505                                                             training_target=training_target, pipeline=pipeline,

/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/models.py in _publish_from_object_cloud(self, model, meta_props, training_data, training_target, pipeline, feature_names, label_column_names, project_id)
   2471 
   2472         except Exception as e:
-> 2473             raise WMLClientError(u'Publishing model failed.', e)
   2474 
   2475     def _upload_autoai_model_content(self, file, url, qparams):

WMLClientError: Publishing model failed.
Reason: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 13 Sep 2022 17:06:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '287', 'Connection': 'keep-alive', 'Server': '---', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {
  "trace": "446d873f1k46c2753849bl09w6d435iae944",
  "errors": [{
    "code": "invalid_request_entity",
    "message": "Invalid request entity: Unsupported model type 'scikit-learn_0.23'",
    "more_info": "https://cloud.ibm.com/apidocs/machine-learning"
  }],
  "status_code": "400"
}

Traceback (most recent call last):
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py", line 254, in _save_scikit_pipeline_model
    model_artifact = self._create_pipeline_model(artifact, query_param)
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py", line 514, in _create_pipeline_model
    model_artifact = self._create_pipeline_model_v4_cloud(model_artifact, query_param)
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/mlrepositoryclient/model_collection.py", line 1148, in _create_pipeline_model_v4_cloud
    model_output = self.repository_api.ml_assets_model_creation_v4_cloud(model_input, query_param,headers)
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/apis/repository_api.py", line 301, in ml_assets_model_creation_v4_cloud
    (data) = self.ml_assets_model_creation_v4_cloud_with_http_info(models_input,query_param, headers, **kwargs)
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/apis/repository_api.py", line 374, in ml_assets_model_creation_v4_cloud_with_http_info
    return self.api_client.call_api(resource_path, 'POST',
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py", line 386, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py", line 206, in __call_api
    response_data = self.request(method, url,
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/api_client.py", line 421, in request
    return self.rest_client.POST(url,
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/rest.py", line 230, in POST
    return self.request("POST", url,
  File "/opt/conda/envs/Python-3.9/lib/python3.9/site-packages/ibm_watson_machine_learning/libs/repo/swagger_client/rest.py", line 202, in request
    raise ApiException(http_resp=r)
ibm_watson_machine_learning.libs.repo.swagger_client.rest.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 13 Sep 2022 17:06:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '287', 'Connection': 'keep-alive', 'Server': '---', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {
  "trace": "446d873f1k46c2753849bl09w6d435iae944",
  "errors": [{
    "code": "invalid_request_entity",
    "message": "Invalid request entity: Unsupported model type 'scikit-learn_0.23'",
    "more_info": "https://cloud.ibm.com/apidocs/machine-learning"
  }],
  "status_code": "400"
}



Publishing model failed.
Reason: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Tue, 13 Sep 2022 17:06:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '287', 'Connection': 'keep-alive', 'Server': '---', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'})
HTTP response body: {
  "trace": "446d873f1k46c2753849bl09w6d435iae944",
  "errors": [{
    "code": "invalid_request_entity",
    "message": "Invalid request entity: Unsupported model type 'scikit-learn_0.23'",
    "more_info": "https://cloud.ibm.com/apidocs/machine-learning"
  }],
  "status_code": "400"
}



Cell 28:
--  ----  -------  ----
ID  NAME  CREATED  TYPE
--  ----  -------  ----

Cell 29:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/1000630000/ipykernel_159/461963156.py in <module>
----> 1 stored_model_details

NameError: name 'stored_model_details' is not defined

Cell 30:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/1000630000/ipykernel_159/224020096.py in <module>
      5 }
      6 
----> 7 published_model_uid = client.repository.get_model_uid(stored_model_details)
      8 created_deployment = client.deployments.create(published_model_uid, meta_props=deploy_metadata)

NameError: name 'stored_model_details' is not defined

Cell 31:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/1000630000/ipykernel_159/2897797406.py in <module>
----> 1 deployment_uid = client.deployments.get_uid(created_deployment)
      2 scoring_endpoint = client.deployments.get_scoring_href(created_deployment)
      3 print(scoring_endpoint)

NameError: name 'created_deployment' is not defined

Cell 37:
--  ----  -------  ----
ID  NAME  CREATED  TYPE
--  ----  -------  ----
----  ----  -----  -------
GUID  NAME  STATE  CREATED
----  ----  -----  -------

Cell 40:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/tmp/1000630000/ipykernel_159/972284368.py in <module>
----> 1 predictions = client.deployments.score(deployment_uid, scoring_payload)
      2 print(json.dumps(predictions, indent=2))

NameError: name 'deployment_uid' is not defined
